### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by alexfedoseev** [nordnet/sass-variable-loader#1]
Hey thanks for this loader! It works great, but there is one issue with it. Any suggestions how to make it play nice with mocha or other unit testing tools?

**Comment by dimchez** [comment]
Hey @alexfedoseev 
How are you using it with mocha? Could you provide an example?

**Comment by alexfedoseev** [comment]
@dimchez Here is the repo to reproduce my case.

Repo: https://github.com/alexfedoseev/css-testing
Tests setup: https://github.com/alexfedoseev/css-testing/tree/master/app/utils/tests

Working branch: [branch](https://github.com/alexfedoseev/css-testing) | [component & specs](https://github.com/alexfedoseev/css-testing/tree/master/app/components/Dummies)
Broken branch: [branch](https://github.com/alexfedoseev/css-testing/tree/sass-variable-loader) | [component & specs](https://github.com/alexfedoseev/css-testing/tree/sass-variable-loader/app/components/Dummies)

In short:

```js
// MyComponent.jsx
import React from 'react';

import css from './MyComponent.scss';
import cssVars from '!!sass-variable-loader!./MyComponent.scss';

export default class MyComponent extends React.Component {
  render() {
    return (
      <div className={css.someClass} />
    );
  }
}
```

To handle CSS Modules there is `css-modules-require-hook`:

```js
// setup.js
import hook from 'css-modules-require-hook';
import sass from 'node-sass';

hook({
  extensions: [ '.scss' ],
  preprocessCss: data => sass.renderSync({ data }).css,
  generateScopedName: '[name]__[local]__[hash:base64:5]',
});

// MyComponent.spec.jsx
describe('<MyComponent />', () => {

  const wrapper = shallowRender(<MyComponent />);

  it('renders `div` with `someClass` className', () => {
    expect(wrapper.find('div')).to.have.className(css.someClass);
  });

});
```

And then run like this:

```bash
mocha --require setup.js --compilers js:babel-register *.spec.jsx
```

But I have no idea how to handle `sass-variable-loader` imports in this case.

**Comment by GU5TAF** [comment]
Hello @alexfedoseev,

After having looked through your code it seems you're not using webpack in the actual tests so unfortunately the loader won't work in that context.

The following is taken from [the webpack docs regarding testing](https://webpack.github.io/docs/testing.html#compile-and-test).
> If you use webpack-specific features it may not possible to run the code with node.js. webpack allows to configure a target system: i. e. you can compile code so that it can run in node.js (configuration option target: "node"). Then use a node.js testing framework to run the bundle.

I think that'd be the best way to get testing working properly but maybe @dimchez has another solution?

**Comment by alexfedoseev** [comment]
@dimchez @GU5TAF I'll play around with mocha's compilers option. Will write back the results here.

**Comment by GU5TAF** [comment]
@alexfedoseev that'd be awesome, thanks!

**Comment by alexfedoseev** [comment]
@dimchez @GU5TAF 

First of all, I suppose this technique will slow down big test suite, but currently there is no other universal way to test modules with webpack-specific code. So here is what I've got.

Mocha gives ability to define custom compiler for each required extension. The first idea was to compile webpack build  in-memory and then pass it to mocha, but I faced the limitations of mocha/webpack APIs. Here is the draft of the compiler:

```js
const path     = require('path');
const webpack  = require('webpack');
const MemoryFS = require('memory-fs');

const config   = require('config/build/webpack.test.config');


require.extensions['.jsx'] = function(module, filename) {
  const buildFileName = path.parse(filename).base;
  const buildConfig = Object.assign({}, config);
  buildConfig.output.filename = buildFileName;

  const compiler = webpack(buildConfig);

  const fs = new MemoryFS();

  compiler.outputFileSystem = fs;

  compiler.run((err, stats) => {
    const build = fs.readFileSync(...); // <--- It must be passed to mocha synchronously
  });

  return module._compile(build, filename);
  //                     ^
  //                     undefined here
});
```

Webpack doesn't have sync version of `compiler.run`. I tried to use `Promises`, `generators`, `async/await`, but no luck — mocha's compiler can't handle `Promises` and ignores `generators`. With tools like `Q` or `co` I can make wrapped function acts as generator, but it can return only `Promise` to outer world — it is not what we (`mocha` actually) want here.

So here is another way to do it. It uses `child_process` to generate webpack build, then `fs` to read its content. Since we have a build-as-a-string, it can be passed to mocha.

Here is the source of compiler:

```js
const fs   = require('fs');
const path = require('path');
const cp   = require('child_process');


require.extensions['.jsx'] = function(module, filename) {

  // Path to webpack binaries
  const webpackBin = (
    path.join(process.cwd(), 'node_modules', '.bin', 'webpack')
  );

  // Path to webpack config for test builds
  const buildConfig = (
    path.join(process.cwd(), 'config', 'build', 'webpack.test.config.js')
  );

  // Temp directory for test builds
  const buildDir = path.join(process.cwd(), 'tmp');

  // Filename for test build
  const buildFileName = path.parse(filename).base;

  try {
    // Check if temp directory exists
    fs.accessSync(buildDir, fs.W_OK);
  } catch (err) {
    // If doesn't - create it
    fs.mkdirSync(buildDir);
  }

  // Compiling build synchronously using `child_process.spawnSync`
  const compiledBuild = cp.spawnSync(webpackBin, [
    filename,
    '--output-path',     buildDir,
    '--output-filename', buildFileName,
    '--config',          buildConfig,
  ]);

  // If something went wrong — throw
  if (compiledBuild.error) {
    throw new Error(compiledBuild.error);
  }

  // Path to compiled build
  const buildPath = path.join(buildDir, buildFileName);

  try {
    // Check if build exists
    fs.accessSync(buildPath, fs.F_OK);
  } catch (err) {
    // Throw if it doesn't
    throw new Error(err);
  }

  // Get build contents
  const build = fs.readFileSync(buildPath, 'utf8');

  // Clean up
  cp.execSync(`rm ${buildPath}`);

  // Pass build to mocha
  return module._compile(build, filename);
};
``` 

Repo with complete setup: https://github.com/alexfedoseev/test-webpack-specific-builds-with-mocha

Worth to check out [webpack config for server/test builds](https://github.com/alexfedoseev/test-webpack-specific-builds-with-mocha/blob/master/config/build/webpack.test.config.js), there are tricky parts there.

Worth a small blog post I guess :)

**Comment by GU5TAF** [comment]
Wow @alexfedoseev that's some really awesome work, well done!
Would love to read a blog post on this :wink:
