### ISSUE TITLE
Imported vars not included in output result

### ISSUE THREAD

**Issue by ixrock** [nordnet/sass-variable-loader#2]
Hi, thanks for the loader. But it's not working with imports..

```
@import 'colors';
@import 'dimensions';
$other: 123;
```

only `other` will be in result.
and due this problem i cannot even reuse variables from imported above in current file..

**Comment by GU5TAF** [comment]
Hey, sorry about the late reply.
I looked into using an AST to get variables instead that would allow me to do imports and the like but it proved too troublesome to be worth it for my use case.
Feel free to take a stab at implementing it yourself and submitting a PR.
